## LinearRegression

In [1]:
!pip install skl2onnx==1.15.0
!pip install onnx
!pip install onnxruntime


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
from skl2onnx import to_onnx


In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder


In [4]:
from sklearn.pipeline import make_pipeline
from skl2onnx import to_onnx
from skl2onnx.common.data_types import StringTensorType
from sklearn.feature_extraction.text import CountVectorizer

from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
 


from skl2onnx.common.data_types import FloatTensorType
from skl2onnx import convert_sklearn
from sklearn.metrics import accuracy_score

In [5]:
dataset= pd.read_csv("temp1.csv")
dataset.head()
print(dataset)


       x1     y
0    57.0  51.0
1    20.0  23.0
2    27.0  23.0
3    16.0   6.0
4    61.0  60.0
..    ...   ...
295  34.0  31.0
296  83.0  34.0
297  71.0  40.0
298  27.0  29.0
299  93.0  92.0

[300 rows x 2 columns]


In [6]:
X_lin = dataset.drop(['y'],axis=1)
y_lin = dataset[['y']]

X_lin_train, X_lin_test, y_lin_train, y_lin_test = train_test_split(X_lin,y_lin,test_size=0.3,random_state=42)



In [7]:
Linear_model = LinearRegression()
Linear_model.fit(X_lin_train,y_lin_train)

pred = Linear_model.predict(X_lin_test)

pred


array([[57.00387757],
       [40.37565417],
       [35.48500023],
       [ 4.18481501],
       [55.047616  ],
       [69.71957782],
       [16.90051526],
       [56.02574679],
       [38.4193926 ],
       [52.11322363],
       [31.57247708],
       [96.1291091 ],
       [80.47901649],
       [ 5.1629458 ],
       [63.85079309],
       [67.76331624],
       [10.05359974],
       [76.56649334],
       [89.28219359],
       [71.6758394 ],
       [75.58836255],
       [ 0.27229186],
       [83.41340886],
       [ 6.14107659],
       [66.78518546],
       [65.80705467],
       [23.74743077],
       [32.55060787],
       [36.46313102],
       [80.47901649],
       [44.28817733],
       [50.15696206],
       [18.85677683],
       [14.94425368],
       [47.22256969],
       [ 9.07546895],
       [25.70369235],
       [33.52873866],
       [12.9879921 ],
       [62.8726623 ],
       [12.9879921 ],
       [68.74144703],
       [35.48500023],
       [93.19471674],
       [49.17883127],
       [21

In [8]:
Linear_model.score(X_lin_test,pred)


1.0

In [9]:
x_newDataSet = np.array([[11],[95],[2],[3]])

# x_newDataSet = {'x1': [1, 2, 3, 4], 'x2': [4, 5, 6, 7]}

x_newDataSet

array([[11],
       [95],
       [ 2],
       [ 3]])

In [10]:
NewPred = Linear_model.predict(x_newDataSet)
NewPred

C:\Users\Z004E89B\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[10.05359974],
       [92.21658595],
       [ 1.25042264],
       [ 2.22855343]])

In [11]:
from sklearn.metrics import mean_absolute_error  
from sklearn.metrics import mean_squared_error  
from sklearn.metrics import r2_score  


In [12]:
def evaluate(y, predictions):
    mae = mean_absolute_error(y, predictions)
    mse = mean_squared_error(y, predictions)
    r_squared = r2_score(y, predictions)
    return mae, mse, r_squared


In [13]:
mae, mse, r2 = evaluate(y_lin_test, pred)
print("MAE:", mae)
print("MSE:", mse)
print("r2 Score:", r2)


MAE: 10.355573128100723
MSE: 249.2859144592342
r2 Score: 0.768017782353889


### onnx


In [14]:
pipe = make_pipeline(
    StandardScaler(),
    LinearRegression()
)
pipe

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [15]:
pipe.fit(X_lin_train, y_lin_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [16]:
Linear_model

LinearRegression()

In [17]:
initial_types=[('x1', FloatTensorType([None, 1]))]
# onx = convert_sklearn(Linear_model, initial_types=initial_type)

initial_types

[('x1', FloatTensorType(shape=[None, 1]))]

In [18]:
onxx_pipeline = to_onnx(pipe, initial_types)
onxx_pipeline

ir_version: 8
producer_name: "skl2onnx"
producer_version: "1.15.0"
domain: "ai.onnx"
model_version: 0
doc_string: ""
graph {
  node {
    input: "x1"
    output: "variable1"
    name: "Scaler"
    op_type: "Scaler"
    attribute {
      name: "offset"
      floats: 49.814285
      type: FLOATS
    }
    attribute {
      name: "scale"
      floats: 0.034879234
      type: FLOATS
    }
    domain: "ai.onnx.ml"
  }
  node {
    input: "variable1"
    output: "variable"
    name: "LinearRegressor"
    op_type: "LinearRegressor"
    attribute {
      name: "coefficients"
      floats: 28.043358
      type: FLOATS
    }
    attribute {
      name: "intercepts"
      floats: 48.019047
      type: FLOATS
    }
    attribute {
      name: "targets"
      i: 1
      type: INT
    }
    domain: "ai.onnx.ml"
  }
  name: "ONNX(Pipeline)"
  input {
    name: "x1"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
          }
          dim {
            dim_value: 1


In [19]:
with open("linearregression.onnx", "wb") as f:
    f.write(onxx_pipeline.SerializeToString())